apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
    app.kubernetes.io/version: "1.5.4"
    app.kubernetes.io/component: web-app
    app.kubernetes.io/part-of: guacamole-stack
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
      app.kubernetes.io/instance: guacamole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacamole
        app.kubernetes.io/instance: guacamole
        app.kubernetes.io/version: "1.5.4"
        app.kubernetes.io/component: web-app
        app.kubernetes.io/part-of: guacamole-stack
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: guacamole-config
        emptyDir: {}
      - name: guacamole-extensions
        emptyDir: {}
      - name: guacamole-lib
        emptyDir: {}
      initContainers:
      - name: setup-extensions
        image: guacamole/guacamole:1.5.4
        command:
        - sh
        - -c
        - |
          echo "Setting up Guacamole extensions..."
          mkdir -p /tmp/guacamole/extensions
          mkdir -p /tmp/guacamole/lib
          cp /opt/guacamole/postgresql/guacamole-auth-jdbc-postgresql-1.5.4.jar /tmp/guacamole/extensions/
          cp /opt/guacamole/postgresql/postgresql-42.6.0.jar /tmp/guacamole/lib/
          echo "Extensions setup complete!"
          ls -la /tmp/guacamole/extensions/
          ls -la /tmp/guacamole/lib/
        volumeMounts:
        - name: guacamole-extensions
          mountPath: /tmp/guacamole/extensions
        - name: guacamole-lib
          mountPath: /tmp/guacamole/lib
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      - name: wait-for-guacd
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z guacd-service 4822; do
            echo "Waiting for guacd service..."
            sleep 5
          done
          echo "Guacd service is ready!"
      - name: wait-for-postgres
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-service -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
          echo "PostgreSQL is ready!"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
      containers:
      - name: guacamole
        image: guacamole/guacamole:1.5.4
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POSTGRESQL_HOSTNAME
          value: "postgres-service"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: GUACD_HOSTNAME
          value: "guacd-service"
        - name: GUACD_PORT
          value: "4822"
        - name: WEBAPP_CONTEXT
          value: "ROOT"
        - name: LOGBACK_LEVEL
          value: "INFO"
        - name: HOME
          value: "/tmp"
        - name: GUACAMOLE_HOME
          value: "/tmp/guacamole"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
        volumeMounts:
        - name: guacamole-extensions
          mountPath: /tmp/guacamole/extensions
        - name: guacamole-lib
          mountPath: /tmp/guacamole/lib
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
