apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd
    app.kubernetes.io/version: "1.5.4"
    app.kubernetes.io/component: daemon
    app.kubernetes.io/part-of: guacamole-stack
spec:
  replicas: 2  # Multiple replicas for high availability
  selector:
    matchLabels:
      app.kubernetes.io/name: guacd
      app.kubernetes.io/instance: guacd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacd
        app.kubernetes.io/instance: guacd
        app.kubernetes.io/version: "1.5.4"
        app.kubernetes.io/component: daemon
        app.kubernetes.io/part-of: guacamole-stack
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: guacd
        image: guacamole/guacd:1.5.4
        ports:
        - containerPort: 4822
          name: guacd
        env:
        - name: GUACD_LOG_LEVEL
          value: "info"
        command:
        - /opt/guacamole/sbin/guacd
        - -f
        - -b
        - "0.0.0.0"
        - -p
        - "/var/run/guacd.pid"
        - -l
        - "4822"
        livenessProbe:
          tcpSocket:
            port: 4822
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 4822
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
        - name: var-run
          mountPath: /var/run
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      - name: var-log
        emptyDir: {}
      restartPolicy: Always
