apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guacd-stateful
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/version: "1.5.4"
    app.kubernetes.io/component: daemon
    app.kubernetes.io/part-of: tutorpro360-stack
spec:
  serviceName: guacd-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: guacd
      app.kubernetes.io/instance: guacd-stateful
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacd
        app.kubernetes.io/instance: guacd-stateful
        app.kubernetes.io/version: "1.5.4"
        app.kubernetes.io/component: daemon
        app.kubernetes.io/part-of: tutorpro360-stack
      annotations:
        prometheus.io/scrape: "false"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: guacd
        image: guacamole/guacd:1.5.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4822
          name: guacd
          protocol: TCP
        env:
        - name: GUACD_LOG_LEVEL
          value: "info"
        - name: GUACD_BIND_HOST
          value: "0.0.0.0"
        - name: GUACD_BIND_PORT
          value: "4822"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 4822
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 4822
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 4822
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - guacd
              topologyKey: kubernetes.io/hostname
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: guacd-headless
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful

---
# Session affinity service
apiVersion: v1
kind: Service
metadata:
  name: guacd-session-affinity
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon-affinity
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour session timeout
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful

---
# Individual services for each guacd pod
apiVersion: v1
kind: Service
metadata:
  name: guacd-0
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon-pod-0
spec:
  type: ClusterIP
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    statefulset.kubernetes.io/pod-name: guacd-stateful-0

---
apiVersion: v1
kind: Service
metadata:
  name: guacd-1
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon-pod-1
spec:
  type: ClusterIP
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    statefulset.kubernetes.io/pod-name: guacd-stateful-1

---
apiVersion: v1
kind: Service
metadata:
  name: guacd-2
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon-pod-2
spec:
  type: ClusterIP
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    statefulset.kubernetes.io/pod-name: guacd-stateful-2
