apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-working
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole-working
    app.kubernetes.io/version: "1.5.4"
    app.kubernetes.io/component: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
      app.kubernetes.io/instance: guacamole-working
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacamole
        app.kubernetes.io/instance: guacamole-working
        app.kubernetes.io/version: "1.5.4"
        app.kubernetes.io/component: web-app
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole:1.5.4
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POSTGRESQL_HOSTNAME
          value: "postgres-service"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_DATABASE
          value: "guacamole_db"
        - name: POSTGRESQL_USER
          value: "postgres"
        - name: POSTGRESQL_PASSWORD
          value: "postgresadmin123"
        - name: GUACD_HOSTNAME
          value: "guacd-service"
        - name: GUACD_PORT
          value: "4822"
        - name: WEBAPP_CONTEXT
          value: "ROOT"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom -Dguacamole.application.title=TutorPro360 -Dguacamole.brand.name=TutorPro360 -Dguacamole.logo.text=TutorPro360"
        - name: TITLE
          value: "TutorPro360 - Educational Remote Access"
        - name: LOGO_TEXT
          value: "TutorPro360"
        - name: BRAND_NAME
          value: "TutorPro360"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Always
