# Persistent Volumes for Guacamole stack
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-new
  labels:
    app: postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/guacamole/postgres-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-extensions-pv-new
  labels:
    app: guacamole
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/guacamole/extensions
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: guacamole
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""  # Use manually created PV
  volumeName: postgres-pv-new
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-extensions-pvc
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
    app.kubernetes.io/component: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use manually created PV
  volumeName: guacamole-extensions-pv-new
