apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: guacamole-pdb
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
    app.kubernetes.io/component: web-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
      app.kubernetes.io/instance: guacamole
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: guacd-pdb
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd
    app.kubernetes.io/component: daemon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guacd
      app.kubernetes.io/instance: guacd
