apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: guacamole
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: database
type: Opaque
data:
  # postgres
  postgres-password: cG9zdGdyZXNhZG1pbjEyMw==  # postgresadmin123 (base64 encoded)
  postgres-user: cG9zdGdyZXM=  # postgres (base64 encoded)
  postgres-db: Z3VhY2Ftb2xlX2Ri  # guacamole_db (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secret
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
    app.kubernetes.io/component: web-app
type: Opaque
data:
  # Default guacamole admin credentials
  guacamole-user: Z3VhY2FkbWlu  # guacadmin (base64 encoded)
  guacamole-password: Z3VhY2FkbWluMTIz  # guacadmin123 (base64 encoded)
