apiVersion: v1
kind: Service
metadata:
  name: tutorpro360-service
  namespace: guacamole
  labels:
    app.kubernetes.io/name: tutorpro360
    app.kubernetes.io/instance: tutorpro360
    app.kubernetes.io/component: web-app
  annotations:
    # Cloud provider annotations (uncomment as needed)
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # For Azure
    # cloud.google.com/load-balancer-type: "Internal"  # For GCP
spec:
  type: NodePort  # Use NodePort for better compatibility, LoadBalancer for cloud providers
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30360  # Custom port for TutorPro360 (360 reference)
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole-working
  sessionAffinity: ClientIP  # Important for TutorPro360 sessions
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: guacamole
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: guacd-service
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
    app.kubernetes.io/component: daemon
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour session timeout
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/instance: guacd-stateful
